# Лабораторная работа №4 по предмету "Теория кодирования".
Выполнили студенты:
Журавская Елизавета группа 6404-010302D и Теплякова Юлия группа 6403-010302D.



In [24]:
import numpy as np

# **Часть 1**

# 4.1 Написать функцию формирования порождающей и проверочной матриц расширенного кода Голея (24,12,8).

In [ ]:
B = [[1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
     [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
     [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
     [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
     [1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
     [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
     [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
     [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
     [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
     [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
     [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]]

In [ ]:
# Порождающая матрица G для кода Голея (24, 12)
def golay_code():
    G = np.zeros((12, 24), dtype=int)
    G[:, :12] = np.eye(12, dtype=int)

    for i in range(12):
        G[i][12:] = B[i]

    return G.astype(int)

In [ ]:
# Проверочная матрица H
def H_matrix_goley(G):
    n = len(G.T)
    k = len(G)
    n_k = n - k

    # Инициализация H матрицы и единичной матрицы
    H = np.zeros((n, n_k), dtype=int)
    I_n_k = np.eye(n_k, dtype=int)

    H[:k, :] = I_n_k
    H[k:, :] = G[:, k:]

    return H

In [ ]:
G_matrix = golay_code()
print("Порождающая матрица G:")
print(G_matrix)
H_matrix = H_matrix_goley(G_matrix)
print("Проверочная матрица H:")
print(H_matrix)

Порождающая матрица G:
[[1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]]
Проверочная матрица H:
[[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 0 1 1 1 0 0

# 4.2. Провести исследование расширенного кода Голея для одно-, двух-, трёх- и четырёхкратных ошибок.

In [ ]:
# Получение синдрома ошибки
def get_syndromes(G, H):
    return G.dot(H) % 2

In [ ]:
# Генерация слова с указанным количеством ошибок
def generate_word_with_n_mistakes(G, error_count):
    u = np.array([1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1])
    print("Исходное сообщение: ", u)

    # Выбор уникальных позиций для ошибок и внесение ошибок в выбранные позиции
    u = u.dot(G) % 2
    mistake_pos = np.random.choice(len(u), size=error_count, replace=False)
    u[mistake_pos] = (u[mistake_pos] + 1) % 2

    return u

In [ ]:
G = golay_code()
H = H_matrix_goley(G_matrix)

In [ ]:
def output_results(word_with_mistake, Syndrome, correct_word_with_mistake, test):
  print("В ходе передачи возникла ошибка\n\nПринято: ", word_with_mistake)
  print("Синдром: ", Syndrome, '\n')
  print("Исправленное кодовое слово: ", correct_word_with_mistake)
  if not np.all(test == 0):
    print("Исправленное слово отличается от отправленного.")
  else:
    print("Исправленное слово совпадает с отправленным.")

1. Однократная ошибка

In [ ]:
# Исправление однократной ошибки
def get_correct_one_mistake(H, syndrome, word):
    # Нахождение индекса строки в H, которая равна синдрому
    indices = np.where(np.all(H == syndrome, axis=1))[0]

    # Исправление ошибки в найденной позиции
    if len(indices) == 0:
        print("Такого синдрома нет в матрице H")
    else:
        index = indices[0]
        word[index] ^= 1

    return word

In [ ]:
print('..::Однократная ошибка::..\n')

# Генерация однократной ошибки, Синдрома и исправление ошибки
word_with_one_mistake = generate_word_with_n_mistakes(G, 1)
Syndrome = get_syndromes(word_with_one_mistake, H)
correct_word_with_one_mistake = get_correct_one_mistake(H, Syndrome, word_with_one_mistake)
test = np.dot(correct_word_with_one_mistake, H) % 2

output_results(word_with_one_mistake, Syndrome, correct_word_with_one_mistake, test)

..::Однократная ошибка::..

Исходное сообщение:  [1 1 0 0 0 0 0 0 1 0 1 1]
В ходе передачи возникла ошибка

Принято:  [1 1 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0]
Синдром:  [1 1 1 0 0 0 1 0 1 1 0 1] 

Исправленное кодовое слово:  [1 1 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0]
Исправленное слово совпадает с отправленным.


2. Двухкратная ошибка

In [ ]:
# Исправление двухкратной ошибки
def get_correct_word_two_mistakes(H, syndrome, word):
    indices = []

    # Поиск индексов, соответствующих синдрому
    for i in range(len(H)):
        # Сравнение с синдромом одной ошибки
        if np.array_equal(syndrome, H[i]):
            indices.append(i)
            break

        # Сравнение с синдромом двух ошибок
        for j in range(i + 1, len(H)):
            if np.array_equal(syndrome, H[i] + H[j]):
                indices.extend([i, j])
                break

        # Если найдены индексы, выход из цикла
        if indices:
            break

    # Исправление ошибок в слове
    if not indices:
        print("Синдром не соответствует ни одной ошибке.")
    else:
        for idx in indices:
            word[idx] ^= 1

    return word

In [ ]:
print('..::Двухкратная ошибка::..\n')

# Генерация двухкратной ошибки, Синдромов и исправление ошибки
word_with_two_mistakes = generate_word_with_n_mistakes(G, 2)
Syndromes = get_syndromes(word_with_two_mistakes, H)
correct_word_with_two_mistakes = get_correct_word_two_mistakes(H, Syndromes, word_with_two_mistakes)
test = np.dot(correct_word_with_two_mistakes, H) % 2

output_results(word_with_two_mistakes, Syndromes, correct_word_with_two_mistakes, test)

..::Двухкратная ошибка::..

Исходное сообщение:  [1 1 0 0 0 0 0 0 1 0 1 1]
В ходе передачи возникла ошибка

Принято:  [1 1 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0]
Синдром:  [0 1 1 0 1 1 0 1 1 1 0 1] 

Исправленное кодовое слово:  [1 1 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0]
Исправленное слово совпадает с отправленным.


3. Трехкратная ошибка

In [ ]:
# Исправление трехкратной ошибки
def get_correct_word_three_mistakes(H, syndrome, word):
    indices = []

    # Поиск индексов, соответствующих синдрому
    for i in range(len(H)):
        if np.array_equal(syndrome, H[i]):
            indices.append(i)
            break

        for j in range(i + 1, len(H)):
            if np.array_equal(syndrome, np.bitwise_xor(H[i], H[j])):
                indices.extend([i, j])
                break
            for e in range(j + 1, len(H)):
                if np.array_equal(syndrome, np.bitwise_xor(np.bitwise_xor(H[i], H[j]), H[e])):
                    indices.extend([i, j, e])
                    break
            if indices:
                break

        if indices:
            break

    # Исправление ошибок в слове
    if not indices:
        print("Синдром не найден в матрице синдромов.")
    else:
        for idx in indices:
            word[idx] ^= 1

    return word

In [ ]:
print('..::Трехкратная ошибка::..\n')

# Генерация трехкратной ошибки, Синдромов и исправление ошибки
word_with_three_mistakes = generate_word_with_n_mistakes(G, 3)
Syndromes = get_syndromes(word_with_three_mistakes, H)
correct_word_with_three_mistakes = get_correct_word_three_mistakes(H, Syndromes, word_with_three_mistakes)
test = np.dot(correct_word_with_three_mistakes, H) % 2

output_results(word_with_three_mistakes, Syndromes, correct_word_with_three_mistakes, test)

..::Трехкратная ошибка::..

Исходное сообщение:  [1 1 0 0 0 0 0 0 1 0 1 1]
В ходе передачи возникла ошибка

Принято:  [1 1 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0]
Синдром:  [0 0 1 1 1 1 0 1 1 1 0 0] 

Исправленное кодовое слово:  [1 1 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0]
Исправленное слово совпадает с отправленным.


4. Четырехкратная ошибка

In [ ]:
# Исправление четырехкратной ошибки
def get_correct_word_four_mistakes(H, syndrome, word):
    indices = []

    # Поиск индексов, соответствующих синдрому
    for i in range(len(H)):
        if np.array_equal(syndrome, H[i]):
            indices.append(i)
            break

        for j in range(i + 1, len(H)):
            if np.array_equal(syndrome, H[i] + H[j]):
                indices.extend([i, j])
                break
            for e in range(j + 1, len(H)):
                if np.array_equal(syndrome, H[i] + H[j] + H[e]):
                    indices.extend([i, j, e])
                    break
                for y in range(e + 1, len(H)):
                    if np.array_equal(syndrome, H[i] + H[j] + H[e] + H[y]):
                        indices.extend([i, j, e, y])
                        break
                if indices:
                    break
            if indices:
                break
        if indices:
            break

    # Исправление ошибок в слове
    if not indices:
        print("Синдром не найден в матрице синдромов.")
    else:
        for idx in indices:
            word[idx] ^= 1

    return word

In [ ]:
print('..::Четырехратная ошибка::..\n')

# Генерация четырехкратной ошибки, Синдромов и исправление ошибки
word_with_four_mistakes = generate_word_with_n_mistakes(G, 4)
Syndromes = get_syndromes(word_with_four_mistakes, H)
correct_word_with_four_mistakes = get_correct_word_four_mistakes(H, Syndromes, word_with_four_mistakes)
test = np.dot(correct_word_with_four_mistakes, H) % 2

output_results(word_with_four_mistakes, Syndromes, correct_word_with_four_mistakes, test)

..::Четырехратная ошибка::..

Исходное сообщение:  [1 1 0 0 0 0 0 0 1 0 1 1]
Синдром не найден в матрице синдромов.
В ходе передачи возникла ошибка

Принято:  [1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0]
Синдром:  [0 1 0 1 1 0 1 0 1 0 1 0] 

Исправленное кодовое слово:  [1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0]
Исправленное слово отличается от отправленного.


# **Часть 2**

# 4.3 Написать функцию формирования порождающей и проверочных матриц кода Рида-Маллера 𝑅𝑀(𝑟,𝑚) на основе параметров 𝑟 и 𝑚.

In [25]:
# Порождающая матрица кода Рида-Маллера
def G_Rid_Maller(r, m):
    if 0 < r < m:
        # Рекурсивные вызовы
        G11_2 = G_Rid_Maller(r, m - 1)
        G22 = G_Rid_Maller(r - 1, m - 1)

        G_left = np.concatenate([G11_2, np.zeros((len(G22), G11_2.shape[1]), dtype=int)])
        G_right = np.concatenate([G11_2, G22])

        return np.concatenate([G_left, G_right], axis=1)

    # Нулевая матрица с единицами
    elif r == 0:
        return np.ones((1, 2 ** m), dtype=int)

    # Верхняя матрица + строка с последней единицей
    elif r == m:
        G_top = G_Rid_Maller(r - 1, m)
        bottom_matrix = np.zeros((1, 2 ** m), dtype=int)
        bottom_matrix[0][-1] = 1
        return np.concatenate([G_top, bottom_matrix])
    else:
        return np.array([])

In [26]:
# Проверочная матрица кода Рида-Маллера
def H_Rid_Maller_i(H, i, m):
    kron_left = np.kron(np.eye(2 ** (m - i), dtype=int), H)
    kron_right = np.kron(kron_left, np.eye(2 ** (i - 1), dtype=int))
    return kron_right

In [27]:
def change_zeros(word):
    for i in range(len(word)):
        if word[i] == 0:
            word[i] = -1
    return word

# 4.4. Провести исследование кода Рида-Маллера 𝑅𝑀(1,3) для одно- и двукратных ошибок.

In [87]:
def generate_word_with_n_mistakes(u, G, error_count):
    print("Исходное сообщение: ", u)

    # Выбор уникальных позиций для ошибок и внесение ошибок в выбранные позиции
    u = u.dot(G) % 2
    mistake_pos = np.random.choice(len(u), size=error_count, replace=False)
    u[mistake_pos] = (u[mistake_pos] + 1) % 2

    return u

In [88]:
def Rid_Maller_3(n, R_M, H_kron):
    u = np.array([1, 1, 0, 0])
    # Генерация слова с ошибками
    w = generate_word_with_n_mistakes(u, R_M, n)
    print("В ходе передачи возникла ошибка\n\nПринято: ", w)
    w_zeros = change_zeros(w)

    # Вычисление произведений с проверочной матрицей
    Hi_1_3 = H_Rid_Maller_i(H_kron, 1, 3)
    Hi_2_3 = H_Rid_Maller_i(H_kron, 2, 3)
    Hi_3_3 = H_Rid_Maller_i(H_kron, 3, 3)

    # Поэтапное вычисление продукта
    w_1 = w_zeros.dot(Hi_1_3)
    w_2 = w_1.dot(Hi_2_3)
    w_3 = w_2.dot(Hi_3_3)

    # Нахождение максимального значения
    max_val_pos = np.argmax(w_3)
    max_val = w_3[max_val_pos]

    # Преобразование позиции максимального значения в двоичный код
    binary = np.binary_repr(max_val_pos, 3)[::-1]

    # Добавление старшего бита в зависимости от значения max_val
    binary = ("1" if max_val > 0 else "0") + binary

    corrected_word = np.array(list(map(int, binary)))
    print("\nИсправленное кодовое слово:", corrected_word)

    # Проверка совпадения отправленного и исправленного слова
    if np.array_equal(corrected_word, u):
        print("Исправленное слово совпадает с отправленным.")
    else:
        print("Исправленное слово не совпадает с отправленным.")

In [89]:
R_M = G_Rid_Maller(1, 3)
print(R_M)

H_kron = np.array([[1, 1],
                   [1, -1]])

[[1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1]]


1. Однократная ошибка

In [90]:
print('..::Однократная ошибка::..\n')
Rid_Maller_3(1, R_M, H_kron)

..::Однократная ошибка::..

Исходное сообщение:  [1 1 0 0]
В ходе передачи возникла ошибка

Принято:  [1 0 1 1 1 0 1 0]

Исправленное кодовое слово: [1 1 0 0]
Исправленное слово совпадает с отправленным.


2. Двухкратная ошибка

In [91]:
print('..::Двухкратная ошибка::..\n')
Rid_Maller_3(2, R_M, H_kron)

..::Двухкратная ошибка::..

Исходное сообщение:  [1 1 0 0]
В ходе передачи возникла ошибка

Принято:  [1 0 0 0 1 0 0 0]

Исправленное кодовое слово: [1 1 0 0]
Исправленное слово совпадает с отправленным.


# 4.5. Провести исследование кода Рида-Маллера 𝑅𝑀(1,4) для одно-, двух-, трёх- и четырёхкратных ошибок.

In [92]:
# Генерация слова с указанным количеством ошибок
def generate_word_with_n_mistakes_RM(u, G, error_count):
    print("Исходное сообщение: ", u)

    # Выбор уникальных позиций для ошибок и внесение ошибок в выбранные позиции
    u = u.dot(G) % 2
    mistake_pos = np.random.choice(len(u), size=error_count, replace=False)
    u[mistake_pos] = (u[mistake_pos] + 1) % 2

    return u

In [93]:
def Rid_Maller_4(n, R_M, H_kron):
    u = np.array([1, 1, 1, 0, 1])
    # Генерация слова с ошибками
    w = generate_word_with_n_mistakes_RM(u, R_M, n)
    print("В ходе передачи возникла ошибка\n\nПринято: ", w)
    w = change_zeros(w)

    # Вычисление произведений с проверочной матрицей
    Hi_1_3 = H_Rid_Maller_i(H_kron, 1, 4)
    Hi_2_3 = H_Rid_Maller_i(H_kron, 2, 4)
    Hi_3_3 = H_Rid_Maller_i(H_kron, 3, 4)
    Hi_4_4 = H_Rid_Maller_i(H_kron, 4, 4)

    # Поэтапное вычисление продукта
    w_1 = w.dot(Hi_1_3)
    w_2 = w_1.dot(Hi_2_3)
    w_3 = w_2.dot(Hi_3_3)
    w_4 = w_3.dot(Hi_4_4)

    # Нахождение максимального значения
    max_val_pos = np.argmax(w_4)
    max_val = w_4[max_val_pos]

    # Преобразование позиции максимального значения в двоичный код
    binary = np.binary_repr(max_val_pos, 4)[::-1]

    # Добавление старшего бита в зависимости от значения max_val
    binary = ("1" if max_val > 0 else "0") + binary

    corrected_word = np.array(list(map(int, binary)))
    print("\nИсправленное кодовое слово:", corrected_word)

    # Проверка совпадения отправленного и исправленного слова
    if np.array_equal(corrected_word, u):
        print("Исправленное слово совпадает с отправленным.")
    else:
        print("Исправленное слово не совпадает с отправленным.")

In [94]:
R_M = G_Rid_Maller(1, 4)
print(R_M)

H_kron = np.array([[1, 1],
                   [1, -1]])

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]


1. Однократная ошибка

In [95]:
print('..::Однократная ошибка::..\n')
Rid_Maller_4(1, R_M, H_kron)

..::Однократная ошибка::..

Исходное сообщение:  [1 1 1 0 1]
В ходе передачи возникла ошибка

Принято:  [1 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0]

Исправленное кодовое слово: [1 1 1 0 1]
Исправленное слово совпадает с отправленным.


2. Двухкратная ошибка

In [96]:
print('..::Двухкратная ошибка::..\n')
Rid_Maller_4(2, R_M, H_kron)

..::Двухкратная ошибка::..

Исходное сообщение:  [1 1 1 0 1]
В ходе передачи возникла ошибка

Принято:  [1 0 0 1 1 0 0 1 0 1 1 0 1 1 0 0]

Исправленное кодовое слово: [1 1 1 0 1]
Исправленное слово совпадает с отправленным.


3. Трехкратная ошибка

In [97]:
print('..::Трехкратная ошибка::..\n')
Rid_Maller_4(3, R_M, H_kron)

..::Трехкратная ошибка::..

Исходное сообщение:  [1 1 1 0 1]
В ходе передачи возникла ошибка

Принято:  [1 1 0 1 1 0 1 1 0 0 1 0 0 1 1 0]

Исправленное кодовое слово: [1 1 1 0 1]
Исправленное слово совпадает с отправленным.


4. Четырехкратная ошибка

In [100]:
print('..::Четырехкратная ошибка::..\n')
Rid_Maller_4(4, R_M, H_kron)

..::Четырехкратная ошибка::..

Исходное сообщение:  [1 1 1 0 1]
В ходе передачи возникла ошибка

Принято:  [0 0 0 1 1 0 0 1 0 0 1 1 1 1 1 0]

Исправленное кодовое слово: [1 1 1 0 1]
Исправленное слово совпадает с отправленным.
